---
fullname: Foundational Cryptography Framework
shortname: fcf
organization: adampetcher
community: true
action: true
dune: false
coqdoc: false

synopsis: Coq library for security proofs of cryptography in the computational model.

description: |-
  FCF is a Coq library containing definitions and theory for security proofs of
  cryptographic schemes in the computational model.

authors:
- name: Adam Petcher
  initial: false

maintainers:
- name: Adam Petcher
  nickname: apetcher

opam-file-maintainer: adampetcher@yahoo.com

opam-file-version: dev

license:
  fullname: Apache 2.0
  identifier: Apache-2.0

supported_coq_versions:
  text: 8.13 or later
  opam: '{(>= "8.13" & < "8.14~") | (= "dev")}'

tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master

tested_coq_opam_versions:
- version: dev
- version: '8.13'

namespace: FCF

keywords:
- name: cryptography
